### ISSUE TITLE
wdi project 4 Ideas

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5_project4#10]
https://github.com/AliTopal89/wdi-project-4

**Comment by AliTopal89** [comment]
Would Employers look down on a dating website?

**Comment by mattscilipoti** [comment]
As discussed, I don't think they would.  They are looking for code quality.  I think ILike or Stopwatch Soccer would be the best fits (as long as you are persisting something for SS).  I'm not sure how you would gather the data for MileTrucks.
