### ISSUE TITLE
Don't understand this code: Uncaught Error: Invalid LatLng object: (NaN, NaN)

### ISSUE THREAD

**Issue by JYamauchi** [ga-dc/wdidc5_project4#100]
I don't understand this code error: Uncaught Error: Invalid LatLng object: (NaN, NaN), what does it means? When I tried to run the Javascript through the html, while trying to call the MapBox API and seed.csv together. In the controller, I put: @restaurants = Restaurant.all. There is the seed for the restaurants' locations as you can see the example below: 

Example from the seed. 
`[#<Restaurant id: 1, name: "STAND N SNACK", permit_id: 1434, address: "1133 15TH ST NW Washington, DC 20005", latitude: #<BigDecimal:7fef87840ef8,'0.3890440268E2',18(27)>, longitude: #<BigDecimal:7fef87840de0,'-0.7703446626E2',18(27)>, yelp_id: nil, created_at: "2015-06-03 19:14:18", updated_at: "2015-06-03 19:14:18”>` 

Javascript in the HTML

`````` <script>

        $("#search").click(function(){
            var latitude = $("#latitude").val();
            var longitude = $("#longitude").val();
            var zoom = $("#zoom").val();

//This is incorrect, I'm just pseudo-coding
//              var response = Api.request
//              var latitude = response["latitude"]

            var marker = L.marker([latitude, longitude], zoom).addTo(map);
            var findLocation = L.setView([latitude, longitude], zoom).addTo(map);

            L.map('map').setView([latitude, longitude], 13)         

            // var marker = L.marker([37, -77], 5).addTo(map);
            var markerHtml = 'This place is weird';
                marker.bindPopup(markerHtml);

        });

        L.mapbox.accessToken = 'pk.eyJ1IjoidHNjaGFlZmZlcjc1MDQiLCJhIjoibGtEVEpDTSJ9.Ii90udJG3hfV3ftGYafKLQ';
        var map = L.mapbox.map('map', 'tschaeffer7504.mbaooln6')
                .setView([38.899, -77.015], 13)
                .addControl(L.mapbox.geocoderControl('mapbox.places'));
        var myLayer = L.mapbox.featureLayer().addTo(map);
        var features = [];

        <% @restaurants.each do |restaurant| %>
            features.push({
            type: 'Feature',
            geometry: {
            type: 'Point',
            coordinates: [<%= restaurant.latitude %>,<%= restaurant.longitude %>]
            },
            properties: {
            name: '<%= restaurant.name %>',
            address: '<%= restaurant.address %>',
                'marker-color': '#000',
                'marker-symbol': 'star-stroked',
                }
            });
        <% end %>

        myLayer.setGeoJSON({
            type: 'FeatureCollection',
            features: features
        });

    </script>```
``````

**Comment by RobertAKARobin** [comment]
`NaN` means "not a number". That means whatever you're passing in as `latitude` and `longitude` aren't numbers. Try doing `console.log(latitude)` to see what they are.

It may be they're strings that LOOK like numbers, in which case use `parseInt(latitude)`, which _parses_ a string as an _integer_.

**Comment by JYamauchi** [comment]
Sorry, I tried to type the console.log(latitude) and it didn't show anything except undefined. hmm

**Comment by RobertAKARobin** [comment]
Keep working backward to wherever you're first setting `latitude`, and `console.log(latitude)` at each step. See if you can figure out where it stops being a number. That's where your problem is.

**Comment by JYamauchi** [comment]
I think I found the problem. It doesn't return the number. It returns like this: `#<BigDecimal:7fe1778db980,'-0.7703446626E2',18(27)>`

How do I only want to get the number in the middle of the array? Is it called slice?

**Comment by RobertAKARobin** [comment]
Huh, interesting. Nope, it's not an array. We covered this waaay early in the class: Ruby stores numbers in a couple different data types, including integers, floats, and "big decimals".  Just call `.to_f` on the variable and it'll turn the BigDecimal into a float.

**Comment by JYamauchi** [comment]
Problem is solved! Thanks!
