### ISSUE TITLE
Embedding youtube video as background

### ISSUE THREAD

**Issue by htylerbrooks** [ga-dc/wdidc5_project4#103]
Having an issue removing the youtube controls and having the video autoplay.

I believe I'm adding the correct text to the end of the youtube string but still not getting the results I want.

Some quick help with this would be greatly appreciated!

Thanks

**Comment by jshawl** [comment]
can we see some code and or a demo?

**Comment by htylerbrooks** [comment]
yea definitely!

<div id="bg_container">
  <iframe id="bg" src="https://www.youtube.com/embed/Thd--viGNjk?list=PLHuZPaPmAjtI-8C-BkT4LiJDzRW7oDB7x?autoplay=1&amp;controls=0"></iframe>
</div>

I add the ? mark at the end of string to try and have the autoplay = 1 and then include the ampersand to try and remove the youtube controls but I'm not getting any results :/

**Comment by htylerbrooks** [comment]
whoops sorry one sec the code would be helpful

**Comment by htylerbrooks** [comment]
<div id="bg_container">
  <iframe id="bg" src="https://www.youtube.com/embed/Thd--viGNjk?list=PLHuZPaPmAjtI-8C-BkT4LiJDzRW7oDB7x?autoplay=1&amp;controls=0"></iframe>
</div>

**Comment by htylerbrooks** [comment]
`<div id="bg_container">
  <iframe id="bg" src="https://www.youtube.com/embed/Thd--viGNjk?list=PLHuZPaPmAjtI-8C-BkT4LiJDzRW7oDB7x?autoplay=1&amp;controls=0"></iframe>
</div>`

**Comment by jshawl** [comment]
change the ? before autoplay to &

**Comment by htylerbrooks** [comment]
Awesome, that worked! I can probably figure out the rest from here.

Thanks again
