### ISSUE TITLE
Whenever not performing runner 

### ISSUE THREAD

**Issue by pmander90** [ga-dc/wdidc5_project4#107]
I set up the whenever gem and got the schedule.rb file set up. I am trying to run a method inside my stock model rb file called "texteveryone" but it will not go through. 

schedule.rb (inside the config folder)

```
every 1.minute do
    runner "Stock.texteveryone"
end
```

Stock.rb (inside app/models folder)

```
class Stock < ActiveRecord::Base
    belongs_to :user

    def self.text(current_user)
        text = "Hello #{current_user.profile.username}, heres your stocks, "
        current_user.stocks.each do |stock|
            text = text + "#{stock.name}: $#{stock.lastprice}. "
        end
        @client= Twilio::REST::Client.new("#{ENV['twilio_sid']}", "#{ENV['twilio_auth']}")
        @client.account.messages.create(
            from: '+12402058377',
            to: current_user.profile.phone_number,
            body: text
        )
    end

    def texteveryone
        Stock.text(User.first)
    end

end
```

after setting up my schedule.rb file I ran "$ whenever --update-cronstab start" in terminal to make the cron job.

**Comment by andrewsunglaekim** [comment]
is the whenever gem running other wise? Can you do a simple puts and see if it occurs in your server logs? Then we can isolate the problem to the gem versus The Stock model. Additionally, try a `binding.pry` outside of your model definition and use them in pry to test and see if your model/method is doing the intended behavior

**Comment by jrhorn424** [comment]
Can you run `crontab -l` and `sudo crontab -l` and share your output?

**Comment by mattscilipoti** [comment]
I might be that 'texteveryone' is not a class method on Stock, it's an instance method.

**Comment by pmander90** [comment]
this is what i get when i run "crontab -l" :+1: 

```
# Begin Whenever generated tasks for: start
* * * * * /bin/bash -l -c 'cd /Users/parmeet/ga/project4/myStocks && bin/rails runner -e production '\''Stock.texteveryone'\'''

# End Whenever generated tasks for: start

# Begin Whenever generated tasks for: /Users/parmeet/ga/project4/myStocks/config/schedule.rb
* * * * * /bin/bash -l -c 'cd /Users/parmeet/ga/project4/myStocks && bin/rails runner -e production '\''Stock.texteveryone'\'''

# End Whenever generated tasks for: /Users/parmeet/ga/project4/myStocks/config/schedule.rb
```

when i run sudo crontab -l i get:

```
crontab: no crontab for root
```

I tried doing "self.texteveryone" as well with no success. and I tried out the method by itself, it works.
