### ISSUE TITLE
made function to preview photo but not sure how to show and save it to profile?

### ISSUE THREAD

**Issue by janicemin** [ga-dc/wdidc5_project4#108]
https://github.com/janicemin/bub

**Comment by andrewsunglaekim** [comment]
Please add code snippet of what you tried. What errors you're running to etc etc.
IE. Your function, how you're using it, what it's currently doing. What you want it do. Additionally showing and saving are two separate concerns and two separate questions.

There's no way to tell what your asking when you only supply an open ended question and your github link.

**Comment by janicemin** [comment]
this is the function that i'm using to choose a local photo and previewing it on my profiles show page. but i'm not sure how to submit it and actually save it to the database so that it will be the user's profile pic. 

```function readURL(input) {
    if (input.files && input.files[0]) {
      var picture = new FileReader();

```
  picture.onload = function (e) {
    $('#img_prev')
      .attr('src', e.target.result)
      .width(150)
      .height(200);
  };

  picture.readAsDataURL(input.files[0]);
}
```

  }
</script>

<input type='file' onchange="readURL(this);" />
  <img id="img_prev" src="#" alt="your image" />```

**Comment by andrewsunglaekim** [comment]
In your onload function(or other functionality that you chose, a submit button, click event, etc etc) you'll have to make an AJAX POST request that updates that object in your backend
