### ISSUE TITLE
Issues overlaying two child divs on parent div

### ISSUE THREAD

**Issue by dmc2015** [ga-dc/wdidc5_project4#109]
I am working with a parent div (an image of a open book) and two child divs. the two children are supposed to overlay on top of the parent div which contains an image. the two child divs are a image and text. so it should be a image on the left side of the open book and a summary on the right side. i am having an issue getting the two child divs to in the right position. ideally i would like it to be responsive also.

Here is some of the source that I have tried.

```

.bookimage{
  position: relative;
}

.story-graphic{
  offset:left;
  position: absolute;
  /*width: 25%;
  height: 25%;*/


}

.story-text{
  offset:right;
  position:absolute;
  /*width: 25%;
  height: 25%;*/
  bottom: 25%;
  left:25%;
  text-align: center;

}
```

```
  <div class="bookimage"><%= image_tag("open-book.jpg") %>

    <div class="story-graphic">
      <img src="<%=@story.graphic%>"/>


    </div>

    <div class="story-text">
      <%= @story.summary %>
    </div>

  </div>


```

**Comment by andrewsunglaekim** [comment]
bookimage needs to be absolute , graphic and text need to be relative

**Comment by andrewsunglaekim** [comment]
actually, bookimage doesn't even need to be absolute

**Comment by andrewsunglaekim** [comment]
absolute is positioning relative to its parent element. I don't think you need positioning on your book image at all

**Comment by RobertAKARobin** [comment]
Hey, Don! Get rid of offset. No idea what that does.

A couple things here: `open-book.jpg` is NOT the parent element of `story-graphic` and `story-text`.

**Comment by RobertAKARobin** [comment]
The way you have it indented makes it confusing. The "tree" of your elements is this:

```
div.bookimage
    img[src="open-book.jpg"]
    div.story-graphic
    div.story-text
```

**Comment by RobertAKARobin** [comment]
I would recommend making all of your images background images in CSS, rather than `img` tags, like this:

```
  <div class="bookimage" style="background-image:<%= asset-url("open-book.jpg") %>;">
    <div class="story-graphic" style="background-image:url(<%= @story.graphic %>);">
    </div>
    <div class="story-text">
      <%= @story.summary %>
    </div>
  </div>
```

```
.bookimage, .story-graphic
{
background-repeat:no-repeat;
background-size:contain;
background-position:center center;
}
```
