### ISSUE TITLE
Using HTTP api on Heroku

### ISSUE THREAD

**Issue by pmander90** [ga-dc/wdidc5_project4#110]
My app works on localhost but once deployed on heroku the ajax requests to the api im using only works if I use "http" but heroku gives me an error saying "mixed content" and trying using "https". How do make heroku go through with the request using http?

**Comment by adambray** [comment]
What API is this?

The general solution to this problem has been covered before from P3... you may need to make the HTTP api call on your backend using HTTParty. You can then pass that data to your front-end using an additional ajax request.

**Comment by pmander90** [comment]
this is the api:

http://dev.markitondemand.com/Api/v2/Lookup/jsonp?input=fb&callback=jQuery1112034951441921293736_1433444607304&_=1433444607305

if nothing else works ill switch it to HTTParty i guess.

**Comment by RobertAKARobin** [comment]
HTTParty is your best bet!
