### ISSUE TITLE
broke geocode and can't access the users nearby 

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5_project4#112]
![screen shot 2015-06-04 at 4 10 18 pm](https://cloud.githubusercontent.com/assets/9599485/7993494/7503d2bc-0ad4-11e5-8a20-4bdd20e2ee0b.png)

**Comment by adambray** [comment]
`@users` is nil in this context. Look at your controller to figure out why.

**Comment by AliTopal89** [comment]
got it working zipcode long, lat was nil, once I updated the zipcode it worked, Thanks
