### ISSUE TITLE
Heroku issue: db migration

### ISSUE THREAD

**Issue by hharper** [ga-dc/wdidc5_project4#114]
when i ran "heroku run rake db:migrate", I got an error because some of my previous migrations were removing columns from my database:

Error message:

```
(1.5ms)  ALTER TABLE "recommendations" DROP "match_id"
PG::UndefinedColumn: ERROR:  column "match_id" of relation "recommendations" does not exist
: ALTER TABLE "recommendations" DROP "match_id"
   (1.0ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
```

Whats the best way to handle? Can i just delete those migration files in my app or is that dangerous?

**Comment by adambray** [comment]
What happens when you run `rake db:migrate:reset`

**Comment by adambray** [comment]
(locally and on heroku)

**Comment by hharper** [comment]
locally everything worked when I did reset so let me try on heroku...

**Comment by hharper** [comment]
ok just ran heroku rake db:reset and it looks like:

```
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"da3gku0lrm7tpf", "username"=>"imkceivybctaws", "password"=>"RYaPTU907kATdk3RGUf4xMW601", "port"=>5432, "host"=>"ec2-54-83-57-86.compute-1.amazonaws.com"}
-- enable_extension("plpgsql")
FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
```

but after it said could not create, it looks like my schema was migrated?

```
-- initialize_schema_migrations_table()
   -> 0.0033s
   (0.9ms)  SELECT version FROM "schema_migrations"
   (1.5ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150602231111')
   (1.7ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150601202737')
   (1.6ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150602030705')
   (1.5ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150602031139')
   (1.5ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150602031103')
   (1.5ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150602180129')
   (1.4ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150602030918')
   (1.4ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150602180042')
   (1.6ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150602145630')
  ActiveRecord::SchemaMigration Load (1.0ms)  SELECT "schema_migrations".* FROM "schema_migrations"
```

**Comment by adambray** [comment]
Oh, right, can you try this instead:

`heroku pg:reset DATABASE`
`heroku run rake db:migrate`

**Comment by hharper** [comment]
after migration i'm getting same error as originally? because doesnt recognize old column value i think

```
Migrating to RemoveMatchIdFromRecommendations (20150601202737)
   (0.9ms)  BEGIN
== 20150601202737 RemoveMatchIdFromRecommendations: migrating =================
-- remove_column(:recommendations, :match_id, :integer)
   (1.3ms)  ALTER TABLE "recommendations" DROP "match_id"

PG::UndefinedColumn: ERROR:  column "match_id" of relation "recommendations" does not exist
: ALTER TABLE "recommendations" DROP "match_id"
   (0.9ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "match_id" of relation "recommendations" does not exist
```

**Comment by jrhorn424** [comment]
You've got a duplication in a migration. Check previous migrations to see if they removed the column you were trying to remove. If they have, you don't need to remove it in the most recent migration.

**Comment by hharper** [comment]
Ok so then I can just delete that migration file where the duplication was happening and re run?

**Comment by jrhorn424** [comment]
@hharper would you mind updating this once your issue is resolved? Will be happy to help again when I return.

**Comment by hharper** [comment]
not at all! thank you :)

**Comment by hharper** [comment]
@jrhorn424 still having issues...i think the last migration i deleted is throwing things off because it was a 'rename' column who's new name attribute can't be found by heroku. I tried checking out to another branch and moving back one commit but still didn't work there. 

If you don't mind letting me know when you all get back that would be great! Kicking myself for not deploying earlier....

**Comment by RobertAKARobin** [comment]
Have you run `heroku run rake db:migrate`? If so, how about `heroku run rake db:reset`?

**Comment by hharper** [comment]
So I can see that my Heroku Recommendation table looks like this: 

```
irb(main):003:0> Recommendation
=> Recommendation(id: integer, user_id: integer, firstMatch_id: integer, status_id: integer)
```

which means that the last migration I had deleted screwed up the Heroku database. Whats the best way to fix? I need to update ‘firstMatch_id’ to ‘first_match_id’ and add the column ‘second_match_id'

**Comment by hharper** [comment]
Should I just generate another migration that does those two things? Locally my database looks fine, its my Heroku db that is the problem...

**Comment by adambray** [comment]
My suggestion is to delete and create a new heroku app
