### ISSUE TITLE
Bootstrap was working, suddenly not

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5_project4#115]
I had a bunch of bootstrap styling, and then I added a jquery gem (chosen-rails) and now none of it works.  I've pushed everything to github (but of course, I didn't commit right before I added the gem...):
https://github.com/Tuzibun/playdate

**Comment by RobertAKARobin** [comment]
What happens when you remove the gem?

**Comment by RobertAKARobin** [comment]
It's working for me. 
![screen shot 2015-06-04 at 4 52 49 pm](https://cloud.githubusercontent.com/assets/6268177/7994289/280777ce-0ada-11e5-9abd-7721ec5abb78.png)

**Comment by Tuzibun** [comment]
wat how is that possible

**Comment by Tuzibun** [comment]
![image](https://cloud.githubusercontent.com/assets/11448967/7994440/79d62cde-0adb-11e5-9ec3-a70c6c29e479.png)

**Comment by Tuzibun** [comment]
I removed the gem and all traces of the gem and I'm still only seeing this: 
![image](https://cloud.githubusercontent.com/assets/11448967/7995167/9edc7cf8-0ae1-11e5-8341-63858be0efc9.png)

**Comment by RobertAKARobin** [comment]
Still working for me, Gwen. I just cloned down your repo, ran `rake db:create` and `rake db:migrate`, and got the same Bootstrappy result as last time. So why not do the same yourself? Make a new folder on your desktop or somewhere, clone your repo into it, and test that out.

**Comment by Tuzibun** [comment]
I'm not using the master branch anymore, I'm using the branch called mailboxer.  I'm rebuilding the mailboxes, and bootstrap is working.  Not sure why the gem broke it, but I'm going to get the mailboxes working again, and then maybe I'll try the gem again later.
