### ISSUE TITLE
having issues with liked_by which is already defined and is referenced on user model 

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5_project4#116]
![screen shot 2015-06-04 at 4 53 16 pm](https://cloud.githubusercontent.com/assets/9599485/7994318/63c8437e-0ada-11e5-99b8-6a961f26e4fc.png)

likes_controller.rb
`def index
    @likes_me = current_user.likes_me
    @liked_users = current_user.liked_users
    current_user.liked_by.update_all(new: false)
  end`

user.rb

```# likes me
  has_many :liked_by, class_name: 'Like', as: :likeable, dependent: :destroy
  has_many :likes_me, through: :liked_by, source: :user

  # I like
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :likeable, source_type: 'User'

``````

```def new_likers_count
    liked_by.where(new: true).count
  end```

like.rb
```class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :likeable, polymorphic: true```

``````

**Comment by jrhorn424** [comment]
I don't think you're allowed to have a column in your database named `new`.

**Comment by jrhorn424** [comment]
The error is looking for a column called `new`. What does `new` false do? Have you run your migrations? Is there a column called `new` in that table?
