### ISSUE TITLE
Project 4 idea

### ISSUE THREAD

**Issue by tsetoung** [ga-dc/wdidc5_project4#12]
https://github.com/tsetoung/Life_Planner_DC5_P4.git

**Comment by RobertAKARobin** [comment]
Please include the learning objectives you turned in yesterday!

**Comment by RobertAKARobin** [comment]
Sorry, I'm stupid, got confused between the project and the EveryConf.

**Comment by tsetoung** [comment]
LOL, no problem....lots going on.  thank you
