### ISSUE TITLE
heroku error

### ISSUE THREAD

**Issue by janicemin** [ga-dc/wdidc5_project4#122]
error message when i try to heroku run rake db:seed after migrating...

i dropped my database and created, migrated and seeded again in the terminal...and the seeded zipcodes are showing up in my database. 

```
ActiveRecord::UnknownAttributeError: unknown attribute 'zipcode' for Profile.
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
```

**Comment by janicemin** [comment]
i'm also running into an error that i hadn't previously where if i created my profile, the zipcode doesn't show for some reason and my ajax request seems to not work because of that....it had earlier...

**Comment by RobertAKARobin** [comment]
Just to be sure: the Profile model has a field called "zipcode", `db:migrate` is correctly adding the `zipcode` column to the Profile table, and `db:seed` is correctly filling in the `zipcode` column with values?

**Comment by RobertAKARobin** [comment]
If you're running into AJAX problems, please open up the console in Chrome and let us know the error you're getting! Also, pushing to Github again would be great so I can take a look at your code.

**Comment by janicemin** [comment]
i pushed it!

**Comment by janicemin** [comment]
i'm not getting an error on the console in chrome...the meetup activity groups that i had been previously seeing just aren't showing. it had been working earlier and i'm not sure why i'm now getting errors about zipcodes. my ajax request is dependent on the profile zipcode.

**Comment by janicemin** [comment]
in my profile table, the seeded zipcode shows up fine

**Comment by RobertAKARobin** [comment]
Seems to be working for me!

![screen shot 2015-06-04 at 8 58 07 pm](https://cloud.githubusercontent.com/assets/6268177/7997533/772a16a0-0afc-11e5-92e2-3e89b729ab8f.png)

**Comment by janicemin** [comment]
would you be able to take a look at my ajax request? i'm not sure why when i enter a different zipcode/update a zipcode, the meetup groups aren't changing accordingly? 

i thought this line of code would make it so that it reads differently each time a new user logs in or i update mine.
url: 'https://api.meetup.com/find/groups?photo-host=public&zip=' + <%=@profile.zipcode%> + '&page=20&country=usa&sig_id=188185019&sig=d9f44a2c374e46c96fe2447861de68aa7750ec29'

**Comment by janicemin** [comment]
i had hardcoded a zipcode earlier but then changed it to this and so assumed it was working fine until the heroku issues popped up...

**Comment by janicemin** [comment]
![screen shot 2015-06-04 at 9 17 05 pm](https://cloud.githubusercontent.com/assets/11448897/7997685/23fbd2c2-0aff-11e5-8229-cb9c4b896114.png)
the zipcode won't even show on the show page for some reason when i made a new user? i don't think i was running into this problem earlier?

**Comment by RobertAKARobin** [comment]
Which page is the AJAX error on?

**Comment by janicemin** [comment]
the profile.html.erb page

**Comment by RobertAKARobin** [comment]
Something else to consider: if zip codes aren't essential to your app, just remove them altogether!

**Comment by janicemin** [comment]
they are because the user is supposed to find activities in the area to preoccupy themselves, haha.

**Comment by janicemin** [comment]
sorry in the show.html.erb file under profiles

**Comment by RobertAKARobin** [comment]
Gotcha

**Comment by RobertAKARobin** [comment]
Where is the AJAX request in this? What is it supposed to do?

**Comment by janicemin** [comment]
<div class = "profile-section"/>
<h2> Hey there, <%=@profile.name%>! <br>
		<h2> You're sooooooo good looking! <h2>
		<h2>Age: <%=@profile.age %> <br></h2>
		<h2>Location: <%=@profile.location %><h2>
		<h2>Phone Number: <%=@profile.phone_number%><h2>
		<h2>Zip Code: <%=@profile.zipcode%><h2>

	<h2> Here's an idea -- instead of calling your ex, try some of these activities in the area!<h2>
		<h2 class="name"></h2>
	
</div>

<script>

$.ajax({
           type: 'GET',
           dataType: 'jsonp',
           jsonp: 'callback',
           url: 'https://api.meetup.com/find/groups?photo-host=public&zip=' + <%=@profile.zipcode%> + '&page=20&country=usa&sig_id=188185019&sig=d9f44a2c374e46c96fe2447861de68aa7750ec29'
               }).done(function(response){
               		for (i = 0; i < response["data"].length; i++){
               				console.log(response["data"][i])
               				console.log(response["data"][i]["name"])
               				$(".name").append("<a href='" + response["data"][i]["link"] + "'>"  + response["data"][i]["name"] + "</a>")

           
               		}
               })
              

</script>


<div class = "friendship-list"/>
<h2>Make Some Friends, <%=@profile.name%> ! <h2>
<ul>
<% for friend in @profile.friends %>
 <li><%= friend.name %></li>
<% end %>
</div>

<div class = "add-friend"/>
<% for possible_friend in @profile.possible_friends %>
	<%= form_tag friendships_path do %>
	  <%= hidden_field_tag 'friend_id', possible_friend.id %>
		<%= submit_tag "Add" %>
		<span> <%= "#{possible_friend.name} as a Friend" %></span>
	<% end %>
<% end %>
</div>

**Comment by janicemin** [comment]
in the middle:

<div class = "profile-section"/>
<h2> Hey there, <%=@profile.name%>! <br>
		<h2> You're sooooooo good looking! <h2>
		<h2>Age: <%=@profile.age %> <br></h2>
		<h2>Location: <%=@profile.location %><h2>
		<h2>Phone Number: <%=@profile.phone_number%><h2>
		<h2>Zip Code: <%=@profile.zipcode%><h2>

	<h2> Here's an idea -- instead of calling your ex, try some of these activities in the area!<h2>
		<script>
$.ajax({
           type: 'GET',
           dataType: 'jsonp',
           jsonp: 'callback',
           url: 'https://api.meetup.com/find/groups?photo-host=public&zip=' + <%=@profile.zipcode%> + '&page=20&country=usa&sig_id=188185019&sig=d9f44a2c374e46c96fe2447861de68aa7750ec29'
               }).done(function(response){
               		for (i = 0; i < response["data"].length; i++){
               				console.log(response["data"][i])
               				console.log(response["data"][i]["name"])
               				$(".name").append("<a href='" + response["data"][i]["link"] + "'>"  + response["data"][i]["name"] + "</a>")
           
               		}
               })
             
</script>
	
</div>


<div class = "friendship-list"/>
<h2>Make Some Friends, <%=@profile.name%> ! <h2>
<ul>
<% for friend in @profile.friends %>
 <li><%= friend.name %></li>
<% end %>
</div>
<div class = "add-friend"/>
<% for possible_friend in @profile.possible_friends %>
	<%= form_tag friendships_path do %>
	  <%= hidden_field_tag 'friend_id', possible_friend.id %>
		<%= submit_tag "Add" %>
		<span> <%= "#{possible_friend.name} as a Friend" %></span>
	<% end %>
<% end %>
</div>

**Comment by RobertAKARobin** [comment]
Gaahh.

**Comment by janicemin** [comment]
not showing for some reason when i copy and paste the file

but it's this:
<script>
$.ajax({
           type: 'GET',
           dataType: 'jsonp',
           jsonp: 'callback',
           url: 'https://api.meetup.com/find/groups?photo-host=public&zip=' + <%=@profile.zipcode%> + '&page=20&country=usa&sig_id=188185019&sig=d9f44a2c374e46c96fe2447861de68aa7750ec29'
               }).done(function(response){
               		for (i = 0; i < response["data"].length; i++){
               				console.log(response["data"][i])
               				console.log(response["data"][i]["name"])
               				$(".name").append("<a href='" + response["data"][i]["link"] + "'>"  + response["data"][i]["name"] + "</a>")
           
               		}
               })
             
</script>
	
</div>

**Comment by RobertAKARobin** [comment]
Github thinks you're writing HTML if you don't do this:

``````
    ```
    Your code
    ```
``````

**Comment by janicemin** [comment]
`<script>
$.ajax({
           type: 'GET',
           dataType: 'jsonp',
           jsonp: 'callback',
           url: 'https://api.meetup.com/find/groups?photo-host=public&zip=' + <%=@profile.zipcode%> + '&page=20&country=usa&sig_id=188185019&sig=d9f44a2c374e46c96fe2447861de68aa7750ec29'
               }).done(function(response){
               		for (i = 0; i < response["data"].length; i++){
               				console.log(response["data"][i])
               				console.log(response["data"][i]["name"])
               				$(".name").append("<a href='" + response["data"][i]["link"] + "'>"  + response["data"][i]["name"] + "</a>")
           
               		}
               })
             
</script>
	
</div>
`

**Comment by janicemin** [comment]
``` <script>
$.ajax({
           type: 'GET',
           dataType: 'jsonp',
           jsonp: 'callback',
           url: 'https://api.meetup.com/find/groups?photo-host=public&zip=' + <%=@profile.zipcode%> + '&page=20&country=usa&sig_id=188185019&sig=d9f44a2c374e46c96fe2447861de68aa7750ec29'
               }).done(function(response){
                    for (i = 0; i < response["data"].length; i++){
                            console.log(response["data"][i])
                            console.log(response["data"][i]["name"])
                            $(".name").append("<a href='" + response["data"][i]["link"] + "'>"  + response["data"][i]["name"] + "</a>")

                    }
               })

</script>

</div>
```

**Comment by RobertAKARobin** [comment]
Your AJAX request is working! Try putting `console.dir(response);` right after the `.done` line. You'll see that you're getting back an error message from the API. `"Authentication credentials are required"`

**Comment by RobertAKARobin** [comment]
The problem with zip codes is in your profiles controller:

```
    private
        def profile_params
            params.require(:profile).permit(:name, :age, :location, :phone_number, :email)
        end

```

See anything missing?

**Comment by janicemin** [comment]
? :p

**Comment by RobertAKARobin** [comment]
Zipcode is missing. What tipped me off was seeing this in the server log: `Unpermitted parameter: zipcode`

**Comment by janicemin** [comment]
ohhhhh!

**Comment by janicemin** [comment]
just a follow-up question about the authentication...does this mean that i have to do something like oauth for twitter/fb but for meetup.com in order for a new user to find groups in their area?

**Comment by RobertAKARobin** [comment]
I don't know anything about their API. Maybe? You'll need to check their API docs.

**Comment by janicemin** [comment]
copy that. thanks!
