### ISSUE TITLE
heroku loading error 

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5_project4#123]
![screen shot 2015-06-04 at 8 37 37 pm](https://cloud.githubusercontent.com/assets/9599485/7997358/9fdad0ba-0af9-11e5-8f9f-9f3d4c1a4f8f.png)

**Comment by AliTopal89** [comment]
I get this error from heroku logs: 
`2015-06-05T00:49:21.810543+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=i-like-dating-website.herokuapp.com request_id=804946da-9817-4a07-ba74-c0b4c74af188 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=`

**Comment by RobertAKARobin** [comment]
Try replacing the `app.listen` portion of your server file with something like this:

```
app.listen(process.env.PORT || 5000, function(){
  console.log("app listening on port 5000")
})
```

**Comment by AliTopal89** [comment]
![screen shot 2015-06-04 at 9 05 24 pm](https://cloud.githubusercontent.com/assets/9599485/7997582/758bd12a-0afd-11e5-96c9-3f4c8ee5b89c.png)

**Comment by RobertAKARobin** [comment]
Did you `heroku restart`?

**Comment by RobertAKARobin** [comment]
Wait a sec. Is this Rails or Node?

https://github.com/AliTopal89/wdi-project-4/tree/master/DatingApp

**Comment by AliTopal89** [comment]
rails

**Comment by RobertAKARobin** [comment]
Oops. I take it back.

**Comment by AliTopal89** [comment]
still have the same error

**Comment by AliTopal89** [comment]
`heroku create i-like-dating-website`
`git remote -v`
`git subtree push --prefix DatingApp heroku master`
`heroku run rake db:migrate`

is what I did

**Comment by AliTopal89** [comment]
then I did heroku open https://github.com/AliTopal89/wdi-project-4

**Comment by AliTopal89** [comment]
then I did heroku open from: https://github.com/AliTopal89/wdi-project-4 *

**Comment by RobertAKARobin** [comment]
Replace the `mailboxer` line in your Gemfile with this:

```
gem 'mailboxer', :git => 'git://github.com/div/mailboxer.git', :branch => 'rails42-foreigner'
```

http://stackoverflow.com/questions/26660640

**Comment by AliTopal89** [comment]
still I get the same error message  :(

**Comment by RobertAKARobin** [comment]
`heroku run bundle install`

**Comment by AliTopal89** [comment]
then should I do heroku run rake db:migrate

**Comment by AliTopal89** [comment]
still same error message :(

**Comment by RobertAKARobin** [comment]
Push to a new Heroku app.

```
git remote remove heroku
heroku create
git add .
git commit -m "whatever"
git push heroku master
heroku run rake db:migrate
heroku open
```

**Comment by AliTopal89** [comment]
`error: Could not remove config section 'remote.heroku'`

**Comment by RobertAKARobin** [comment]
Wat. That happens after `git remote remove heroku`?

**Comment by AliTopal89** [comment]
yep

**Comment by AliTopal89** [comment]
ok sort of worked, 
thank you Robin

**Comment by AliTopal89** [comment]
adding `gem 'mailboxer', :git => 'git://github.com/div/mailboxer.git', :branch => 'rails42-foreigner'`
definitely helped
after Robin's help I just deleted the app from heroku and created a new one
