### ISSUE TITLE
heroku loading error

### ISSUE THREAD

**Issue by APARK87** [ga-dc/wdidc5_project4#125]
https://lit-escarpment-5324.herokuapp.com/

(process:13250): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

**Comment by RobertAKARobin** [comment]
Try replacing the `app.listen` portion of your server file with something like this:

```
app.listen(process.env.PORT || 3000, function(){
  console.log("app listening on port 3000")
})
```

**Comment by APARK87** [comment]
im using rails

**Comment by RobertAKARobin** [comment]
Oops.

**Comment by RobertAKARobin** [comment]
Have you pushed to Github recently? I'm going to clone your code and try it myself.

**Comment by APARK87** [comment]
my last push was the one right before beginning the deploy process

**Comment by RobertAKARobin** [comment]
Great

**Comment by RobertAKARobin** [comment]
Well, I'm getting the same error, so this is progress.

**Comment by RobertAKARobin** [comment]
```
project_4 $ heroku run rails console
Running `rails console` attached to terminal... up, run.7442
/app/app/controllers/passwords_controller.rb:1:in `<top (required)>': uninitialized constant Users (NameError)
```

**Comment by APARK87** [comment]
mm

**Comment by APARK87** [comment]
ill check it out, was running okay on localhost

**Comment by RobertAKARobin** [comment]
That's it! In that file, change "Users" to "User". It's working here: https://agile-ocean-2089.herokuapp.com/

**Comment by APARK87** [comment]
ahh icic, alrighty; also am i good to push further changes ?

**Comment by RobertAKARobin** [comment]
Sure! Don't wait on me.
