### ISSUE TITLE
running into the same issue with heroku deployment

### ISSUE THREAD

**Issue by janicemin** [ga-dc/wdidc5_project4#128]
getting this error when i try to seed and deploy heroku

rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'zipcode' for Profile.
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'

**Comment by RobertAKARobin** [comment]
What are you doing that triggers the error?

**Comment by RobertAKARobin** [comment]
Oh, never mind.

**Comment by RobertAKARobin** [comment]
What do you get when you run:

```
heroku run rails console
```

and then:

```
Profile.all
```

(Note: to exit the console type `exit`)

**Comment by RobertAKARobin** [comment]
It worked on my computer! See here:

https://pure-taiga-6211.herokuapp.com/users/sign_in

When in doubt, just `git remote remove heroku` and `heroku create` all over again.
