### ISSUE TITLE
merging my branch back to master: git issues

### ISSUE THREAD

**Issue by seekpeace** [ga-dc/wdidc5_project4#131]
15:24:14-seekpeace~/projects/portfolio_guard (master)$ git checkout -b actionmailer
Switched to a new branch 'actionmailer'
i did the above an eon ago and now when i do 
22:33:33-seekpeace~/projects/portfolio_guard (actionmailer)$ git checkout master
error: pathspec 'master' did not match any file(s) known to git.

git headache to the bitter end and thank you for any assist.

**Comment by RobertAKARobin** [comment]
What's the output of `git branch -av`?

**Comment by seekpeace** [comment]
22:48:40-seekpeace~/projects/portfolio_guard (actionmailer)$ git status
On branch actionmailer
nothing to commit, working directory clean
22:48:42-seekpeace~/projects/portfolio_guard (actionmailer)$ git checkout master
error: pathspec 'master' did not match any file(s) known to git.
22:48:45-seekpeace~/projects/portfolio_guard (actionmailer)$ git branch -av
- actionmailer 00e7cb2 trying again
  22:49:14-seekpeace~/projects/portfolio_guard (actionmailer)$

**Comment by RobertAKARobin** [comment]
It's because you only have one branch, `actionmailer`

**Comment by RobertAKARobin** [comment]
You don't have a `master` branch.

**Comment by RobertAKARobin** [comment]
You can rename your current branch by using `git branch -m "new name here"`

**Comment by seekpeace** [comment]
but i did this earlier:
15:24:14-seekpeace~/projects/portfolio_guard (master)$ git checkout -b actionmailer
Switched to a new branch 'actionmailer'
but ok.

**Comment by seekpeace** [comment]
ok i just renamed it to master, thanks Robin!
