### ISSUE TITLE
Project 4 Idea

### ISSUE THREAD

**Issue by nhashmi** [ga-dc/wdidc5_project4#14]
For project 4, I want to create an app that makes it easy for a person (or a group of people) to track possible housing rentals, sort them by the things they a) need to have and b) want to have, and then pick the home that best fits their needs. I will also provide information about the home's price relative to nearby properties, demographic info, and other information about the area.

**Comment by jrhorn424** [comment]
I like your idea of matching people with properties. It will provide an interesting challenge coding (and hopefully testing!) back-end matching logic. I'll be interested to see the matching algorithm as it develops.

For comp data, I suggest using an API from a service like Zillow. Not sure how challenging that will be.

This has the potential to get very complex, so we should talk about a plan of work at some point.

**Comment by nhashmi** [comment]
That'd be great. I was planning to use Zillow--it looks like the APIs return a lot of information.
