### ISSUE TITLE
Project #4

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5_project4#15]
I'd like to create an app that is something like a dating app, but for children's play dates.  Elementary schools (especially private schools), publish a directory of family contact information.  The main purpose of the directory is to facilitate birthday parties, and play dates.  However, this can cause awkward situations when a family doesn't want their contact information published or if a family doesn't want to have a play date with another.

My app would allow administrators to create a "classroom" of students with their family contact information.  When one parent wants to set up a playdate with another child, they would send a private message to that person's parents.  The recipient could then "swipe left or right" to accept or decline the offer.  Once the offer is accepted, the involved parties can exchange contact information.

**Comment by andrewsunglaekim** [comment]
I like it! Looking forward to how you'll implement this! ... Maybe there should be some sort of vetting system.. wouldn't want any stars of the chris hansen show using your app.
