### ISSUE TITLE
Heroku Deployment Issue, Error code H20 & H10

### ISSUE THREAD

**Issue by luminousbeam** [ga-dc/wdidc5_project4#151]
The print screen below is of the heroku log errors I am showing when trying to load my site, I am showing errors "H20 - App boot timeout
The router will enqueue requests for 75 seconds while waiting for starting processes to reach an “up” state. If after 75 seconds, no web dynos have reached an “up” state, the router logs H20 and serves a standard error page." and "H10 - App crashed
A crashed web dyno or a boot timeout on the web dyno will present this error."

![snip20150605_1](https://cloud.githubusercontent.com/assets/9014849/7999831/63562e74-0b20-11e5-9db6-b29f206242d1.png)

**Comment by jrhorn424** [comment]
This usually happens when you've created an infinite loop somewhere in your app.

**Comment by luminousbeam** [comment]
I was able to resolve my deployment issue by adding this snippit of code to my index.js (others may have called it app.js) file, we can close this issue:

``` javascript
app.listen(process.env.PORT || 3000, function(){
  console.log("Express server listening on port %d in %s mode", this.address().port, app.settings.env);
});
```

http://stackoverflow.com/questions/18679690/heroku-nodejs-app-with-r10-h10-and-h20-errors
