### ISSUE TITLE
Project 4 video - TS and JY

### ISSUE THREAD

**Issue by mugshepherd** [ga-dc/wdidc5_project4#159]
a little longer than 5 minutes.  https://youtu.be/BgJW_PlGe2w

**Comment by RobertAKARobin** [comment]
Toooobeeeeeee.

**Comment by mugshepherd** [comment]
Robin?

**Comment by RobertAKARobin** [comment]
You officially have the longest video.

**Comment by mugshepherd** [comment]
Go out with a bang, right?
