### ISSUE TITLE
Project 4 idea

### ISSUE THREAD

**Issue by michaelkendall** [ga-dc/wdidc5_project4#16]
I want to create an app that simplifies the process of taking bar inventory. I would like to incorporate a plugin that takes data and transfers it to an excel spreadsheet. I will also use an api that determines the weight of the spirit and transfers that weight into how much is left in the bottle.

**Comment by jshawl** [comment]
:+1: Awesome idea mike! Please let me know if you'd like more feedback or direction on this project - otherwise you're good to go!

**Comment by michaelkendall** [comment]
Thanks Jesse! I would like to chat more about my idea with you if possible. Can we meet tomorrow at some point?

**Comment by jshawl** [comment]
Sure! Come grab me after lunch when you're not in the portfolio standup

On Wednesday, May 27, 2015, michaelkendall notifications@github.com wrote:

> Thanks Jesse! I would like to chat more about my idea with you if
> possible. Can we meet tomorrow at some point?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/wdidc5_project4/issues/16#issuecomment-106112739
> .

## 

Jesse Shawl
http://jshawl.com

**Comment by jshawl** [comment]
http://railscasts.com/episodes/362-exporting-csv-and-excel
