### ISSUE TITLE
w11d2 hw Project 4 pitch

### ISSUE THREAD

**Issue by luminousbeam** [ga-dc/wdidc5_project4#17]
I got the idea to make a synthesizer/drum machine (using JS, jQuery, Node.js, Express and possibly Backbone) that will loop and record what you play.  I also intend to add at least one demo so that people get an idea of the potential this instrument can have. I noticed that some people in the past have dabbled with a similar idea, but I think I can make mine be different than those created in the past.

**Comment by jshawl** [comment]
:+1: AWESOME!!! I feel like this will be a very challenging assignments - as there are many moving parts. Have you thought about how you'll play sound on the web - or how you might implement websockets to let multiple people play at once?

Please let me know if you'd like more feedback or direction on this project!
