### ISSUE TITLE
Project 4 Pitch

### ISSUE THREAD

**Issue by tpeters0** [ga-dc/wdidc5_project4#18]
Revisiting my Domestic Violence awareness idea ... Focusing on front end techniques, including Backbone, to create an interactive method for the user to gain insight into the cycle of domestic abuse and related issues.

**Comment by jshawl** [comment]
:+1: Will you be implementing some sort of CRUD functionality? I know we discussed adding a quiz before - but want to make sure you have an application that _requires_ a back end
