### ISSUE TITLE
Project 4 Pitch

### ISSUE THREAD

**Issue by ryankeiper** [ga-dc/wdidc5_project4#19]
So, for most of my projects so far, I've made something game-related. There was Battleship, there was chess, but now, I want to top them. Why another game? For the wow factor! Everyone loves a fully functional awesome game. So what do I want to make this time?

Asteroids. https://www.youtube.com/watch?v=WYSupJ5r2zo

Deployed on Heroku. Two player vs mode with websockets. Graphically updated for the 21st century.

Here's hoping it turns out awesome.

**Comment by jshawl** [comment]
:+1: Love the multiplayer and websockets idea. I feel like the hardest part will be the gameplay itself - drawing the asteroids and fighter planes.

Have you done any research on how you might implement this? 

Just want to make sure you don't spend too much time on an implementation detail
