### ISSUE TITLE
JYamauchi Project 4

### ISSUE THREAD

**Issue by JYamauchi** [ga-dc/wdidc5_project4#2]
https://github.com/JYamauchi/GA-Project4

**Comment by RobertAKARobin** [comment]
:+1:

**Comment by RobertAKARobin** [comment]
I don't see your elevator pitch. Taken from the README:

> SUBMIT a three-sentence, 30-second pitch of your project idea as an issue to THIS repo before 9:00 AM Wednesday.

https://github.com/ga-dc/wdidc5_project4
