### ISSUE TITLE
Project 4 Pitch: Convergence

### ISSUE THREAD

**Issue by nbumbarger** [ga-dc/wdidc5_project4#20]
A full-screen map application with AJAX controls, Convergence allows an account holder to define a convergence area either explicitly or based on their current location and send it to friends, to quickly arrange meetups and track one another’s status. Upon defining an area, the originating user can send a link to the convergence area to friends, at which point their version of the map begins to track the location of friends who have accepted the link as well as offering an interface to add group messages to the shared map. Each of the recipients' maps show the same information but also displays walking or driving directions, making the mechanics of gathering together fast, intuitive, and fun– even when the destination is unfamiliar.

**Comment by jrhorn424** [comment]
I'd be skeptical of the scope if I hadn't already seen a map application from you. This is an exciting idea! Let's talk about plan of work when you have a moment.

Please open another issue once you have your repo, wireframes, and user stories.
