### ISSUE TITLE
final project 

### ISSUE THREAD

**Issue by nclevine** [ga-dc/wdidc5_project4#21]
My goal is to make a collaborative, realtime, social drawing app for mobile. It will be a bit like the drawing component of snapchat, except instead of disappearing quickly it is something that users will build upon over time. A user can have shared drawing boards with each of his/her friends, and users can create group boards as well.

**Comment by adambray** [comment]
Hey Noah,

I think this is a great idea, and definitely do-able, though it will probably be tough. My advice would be to focus on an MVP for desktop first, and then try to optimize for mobile web.

You may want to look at this, which one of my students built back in 2013 (so long ago!)
https://github.com/enylund/drawingApp

-Adam
