### ISSUE TITLE
Project 4 Pitch

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/wdidc5_project4#22]
I will be doing a choose your own adventure style in-browser game using javascript, html5 and it's canvas feature, and a game engine. At this point,  I believe it will have a node/express backend with mongodb, utilizing web sockets for quick response times. I hope to have one full level finished.

**Comment by jrhorn424** [comment]
I'm glad we got to speak about this yesterday. I really like the idea! Let me know if you'd like to discuss it further.
