### ISSUE TITLE
Project 4 idea(s)

### ISSUE THREAD

**Issue by DamonMd** [ga-dc/wdidc5_project4#27]
stuck between 2 project ideas.
1. Create a portfolio website for my sister. She's currently pre-med undergrad, but has won several competitions for t-shirt designs and artwork for children's books. While she's made some money of this, she would do better to cut out the middle man and showcase her abilities herself on her own website.
2. The second idea is for a travel planning app. Usually when I would travel to different cities I'd have one google doc will all my flight info/emails, another for all the sights i'd want to see/restaurants to visit, and maybe a saved google map with marker points for the attractions. I'd like to combine all this into a simple, easy to use app that would allow you to store all this info in one location with the ability to sort your itinerary by day.

**Comment by mattscilipoti** [comment]
I'm not sure how to work examples of all the aspects of your learning into the portfolio website.  Plenty of opportunity for that in the travel app.  The tough part there is cutting scope and building one piece at a time to make sure you have something to present.
