### ISSUE TITLE
Project 4 - Haleigh

### ISSUE THREAD

**Issue by hharper** [ga-dc/wdidc5_project4#30]
WDIDC5 - A COMPILATION!

For my final project, I want to compile allllll notes, exercises, screencasts and code challenges onto one unified website. Currently our information is spread out all over GitHub and on scattered notes, so I want to take all of this information and put it in one user-friendly site that all WDIDC5ers can access with ease and for all future reference. 

Instructors, what do you think? I would focus on the userability of this site and show how I can take large amounts of information and break it down/organize it into digestible pieces. My only concerns:
1. Would need to outline specifically what coding features I would be utilizing...is this enough of a portfolio piece? In my mind it is, but it is more so about organizing information than it is showing off specific, flashy coding skillz....
2. Would need to get permission from everyone to publish their screencasts/notes on my site (most stuff is online anyway, so shouldn't be difficult but want to confirm)

**Comment by andrewsunglaekim** [comment]
I think this idea is AWESOME. Looking forward to user stories. I think it'll be relatively simple to implement, however, this is one of those things where the monies in the data. So seeding might be an arduous task...

**Comment by hharper** [comment]
Thanks Andy! Realized today I would basically be creating the Odin Project (http://www.theodinproject.com/home) but with all of our information...

Would love to talk about the best frameworks to build this on! And yes seeding all that data :flushed: I'll message you about scheduling one-on-one tomorrow :)

USER STORIES: https://trello.com/b/bqEL91X5/project4-the-milkncookies-project

**Comment by andrewsunglaekim** [comment]
I lik the user stories, but I would also like them to me more granular and actionable. IE 
A user can login in order to access content
a user can access content by language so that they can peruse through WDI materials
a user can access screencasts/instruction videos so that they can view them at their liesure

these are just an example. But the basic idea is something actionable and granular and the reason for the user story at the end. Let me know when you wanna meet! Also make a repo! and do some wireframes/sketching

**Comment by hharper** [comment]
Thank you Andy! When are you available later today? I have my portfolio
review thing from 1:30-2:30 so I'm free any time after that!

**Comment by andrewsunglaekim** [comment]
Haleigh! need your new user stories/ERD's/wireframes when you get a chance! thanks!

**Comment by hharper** [comment]
Hey Andy! Please find my user stories on Trello: https://trello.com/b/GTvAkQrT/tickletush  (also linked in my README) and my ERD uploaded to my github repo: https://github.com/hharper/ga_project4_tickletush_dating_app (as ERD.JPEG).

Thanks!
