### ISSUE TITLE
Project 4 ideas

### ISSUE THREAD

**Issue by 0xZakk** [ga-dc/wdidc5_project4#31]
I've got a couple of Ideas:
1. Tinder for house hunting
2. Date night / night out generator: a user fills out a form and gets an automated itinerary for a date or night out.
3. Competi-give: users create groups to compete to raise money for a charity they select

**Comment by adambray** [comment]
(Met with Zack in person to discuss ideas. All 3 are viable, he's going to flesh them out tonight (ERDs, etc) to help decide which to pursue for P4.
