### ISSUE TITLE
CoverCreater or Collabo

### ISSUE THREAD

**Issue by Freetown5** [ga-dc/wdidc5_project4#32]
30 Second Pitch

A cover letter template creater that allows the user (normally a job seeker, redundant I know) to create a template for cover letters, possibly thank you notes as well (still can't let this go), that they can save and reuse later. They will be able to use these templates by adding company relavant information to open spots in the template madlib style which they can automatially send via email to the recipeient they wish to receieve it.

or (still mulling it over)

Collaborate

30 Second Pitch

A site that developers and designers can use to get feed back from project mangers, marketers, lawyers and other workers involved in the business side of tech on project already in development.

**Comment by andrewsunglaekim** [comment]
I like both ideas! looking forward to user stories/domain model for either!
