### ISSUE TITLE
project 4 idea

### ISSUE THREAD

**Issue by philw214** [ga-dc/wdidc5_project4#33]
I want to make a travel photoblog app that allows a user to geotag photo locations, have those location show up on a map, and allow a user to view photos by specific location.  A user would also be allowed to comment on photos.

**Comment by adambray** [comment]
Hey Phil,

This sounds like a great idea! Do you know what tools you're going to use for geotagging / mapping? I've heard good things about the MapBox API (you can ask Nick B. about it I bet), and I know geocoder is a good Gem for geotagging arbitrary objects in ruby (I'm actually a contributor to that gem!)

-Adam

**Comment by philw214** [comment]
I was leaning towards Mapbox, but I'm also doing some research into WebGL
3D rendering.  Can I talk to you about what I want to do with it tomorrow?

**Comment by adambray** [comment]
Sure! I suspect map box is the best bet given the time constraints. But let's talk.
