### ISSUE TITLE
Project 4 idea

### ISSUE THREAD

**Issue by julia-rose** [ga-dc/wdidc5_project4#34]
I'm still pretty undecided, but I was thinking of making an app for guided, "gentle" goal-setting that focuses on building small habits over a long period of time. The app would have a calendar interface and a progress/stats feature. The other idea I was thinking over was an app to help actors learn their lines, but this would require the actor to have a text file of the play that they're in (which really would only work for old plays like Shakespeare, nothing that's under current copyright protection). Don't know if that's prohibitive to making the app...?

UPDATE: After briefly chatting with Jesse and Adam, I now want to go in a completely different direction! I'd like to make an app for teachers and students. During a lesson, students can click a button (or tap from their phone) if they're confused or otherwise feeling lost. This alerts the instructor, with varying levels of alert-itude depending on the number of students who click within a given timeframe. There will also be an option for the instructor to initiate a "fist of five" class poll, for which the students can respond with their comfort level 1-5 on the current topic. Additionally, questions from students can come in to the instructor's screen at any time during the lesson as an alternative to hand-raising if the student is shy or embarrassed to be asking, and the instructor can then address the questions as they see fit.

**Comment by jrhorn424** [comment]
Excited to see where this goes. Let me know if you'd like to discuss your idea 1:1.
