### ISSUE TITLE
Project 4 vision

### ISSUE THREAD

**Issue by Karen-O** [ga-dc/wdidc5_project4#35]
My project will be based on the methods of Marie Kondo, famed Japanese organizing guru who was featured in New Yorker magazine in November 2014; her best-known "rule" is that the first step to any organizing project MUST be taking everything out of its place and laying it on the floor to properly analyze and take further action on. For instance, all books on a bookshelf must first come off it, at the same time, if you want to organize said bookcase once and for all. This can be seen as analogous to "step 1" of my program. Step 2 I will base on the common [American] de-cluttering formula of dividing your items into 4 piles: Keep, Donate, Trash, and Wait-a-month. Therefore, my program will at its core be a possessions-management (and ideally minimizing) aid. It can also be used as a home inventory system or closet system, as additional functionalities that would easily derive from the first. 

In order for this to work as I'd like, the ability for users to upload images is pretty important. Since this is Project #4, I'd like to deploy to my own domain name (with paid hosting service) instead of Heroku, given the latter's limitations. It will run on Rails, which InMotion Hosting supports.

**Comment by jrhorn424** [comment]
Decluttering and minimalism are hot topics, so this could be a very timely project. However, It isn't clear to me how a web app will support this process. Is the app just used to upload images and take inventory? What parts of your app will support organization or decluttering?

Please open another issue when you have your repo, wireframes, and user stories. I'll be able to provide more specific feedback at that time.

**Comment by Karen-O** [comment]
Can I ask you 2 quick questions?

First, I was really intrigued hearing about Meteor this morning, and would
welcome an opportunity to teach myself something new as well as diversify
my portfolio a bit. Would it generally be safe to say that I could achieve
the same functionalities / "quality" in Meteor as I'd expect from Rails and
Node? The answer seems to be yes, but I don't want to dive in without a
more authoritative opinion on the matter.

Also, I didn't want to make any assumptions about the photo-uploading issue
with using Heroku. In the past, deployment to Heroku has been
non-negotiable. If that's not the case this time, then I can plan my app on
different terms (more ideal for what I'd like to build). Either way, I'll
adapt to the requirements; I just need to be clear on what they are
exactly. (At which point I can tell you way more!)

Thanks a lot.
Karen

**Comment by jrhorn424** [comment]
Thanks for writing back, @Karen-O. As we discussed late last week, Meteor would be fine, but I think you wanted to stick with either MEAN or Rails?

Additionally, hosting somewhere other than heroku is fine. The most important thing is that the app is deployed.

I'd still like to see some planning documents, so we have something to discuss during 1:1.

**Comment by Karen-O** [comment]
Yes, I do want to stick with MEAN or Rails for this one. It'll be Rails,
because in terms of database, PSQL/ActiveRecord will be more appropriate I
think.

FWIW, I'm going to rework my Project 3 a bit and do that one in Meteor.

All the planning docs will be ready; I'm just converting them from
hand-drawn into a far more professional (and readable) set using a program
called draw.io. It has a library for mocking up Bootstrap projects, and a
fast-enough learning curve.

Re: deployment to Heroku, that won't be an issue for this new project 4
idea, because user uploads won't be necessary. I might still RATHER deploy
elsewhere, but I'm not wed to the idea and can definitely just stick with
what's familiar (Heroku); then maybe if there's  time at the end I'll
switch to my paid hosting/domain.

Thanks for writing back, @Karen-O https://github.com/Karen-O. As we
discussed late last week, Meteor would be fine, but I think you wanted to
stick with either MEAN or Rails?

Additionally, hosting somewhere other than heroku is fine. The most
important thing is that the app is deployed.

I'd still like to see some planning documents, so we have something to
discuss during 1:1.
