### ISSUE TITLE
Project 4

### ISSUE THREAD

**Issue by APARK87** [ga-dc/wdidc5_project4#38]
Still not decisive but I may try to make a site geared towards learning history in a convenient way. The user will be able to select a region, and then view that regions historical timeline. User can then filter through certain periods, events, etc. User will also be able to add to the timeline (like wiki in a way).

**Comment by mattscilipoti** [comment]
Sounds good.  I have seen a few really nice jQuery Plugins (and similar) for visualizing timelines.
