### ISSUE TITLE
Project 4 idea for TS

### ISSUE THREAD

**Issue by mugshepherd** [ga-dc/wdidc5_project4#4]
Using data from the InspectionMapper website (which scrapes data from the DC Department of Health, as well as Yelp and Open Tables) I want to build a site that presents how well local restaurants in DC have done on their health inspections.  I would like to make it responsive for PC, tablet, and mobile viewing.  Users may be able to authenticate, save favorites, comment on restaurants, and respond to comments.  

API:  http://grahamimac.com/inspectionmapper/#page=apiPage

**Comment by jshawl** [comment]
:+1: Excellent idea!!! You're good to go!
