### ISSUE TITLE
w11d02 homework

### ISSUE THREAD

**Issue by julia-rose** [ga-dc/wdidc5_project4#40]
So, I edited my previous issue with my new project pitch, but here it is again just in case:

After briefly chatting with Jesse and Adam, I now want to go in a completely different direction! I'd like to make an app for teachers and students. During a lesson, students can click a button (or tap from their phone) if they're confused or otherwise feeling lost. This alerts the instructor, with varying levels of alert-itude depending on the number of students who click within a given timeframe. There will also be an option for the instructor to initiate a "fist of five" class poll, for which the students can respond with their comfort level 1-5 on the current topic. Additionally, questions from students can come in to the instructor's screen at any time during the lesson as an alternative to hand-raising if the student is shy or embarrassed to be asking, and the instructor can then address the questions as they see fit.

Here's my repo with user stories! I'll add the pictures of my wireframes later tonight, stay tuned. 
https://github.com/julia-rose/wdi_project4

**Comment by jrhorn424** [comment]
These look great. I'd like to discuss scope once I've seen your wireframes and ERDs. This will be a good opportunity to use websockets and a front-end framework/library.

Please ping me with a message when you've uploaded your wireframes.
