### ISSUE TITLE
Project 4 link for TS and JY

### ISSUE THREAD

**Issue by mugshepherd** [ga-dc/wdidc5_project4#43]
https://github.com/mugshepherd/project4

A user can see a map.  
A user can interact with the map
A user can see points on a map indicating restaurants in the map view.
A user can select a restaurant
Upon selecting a restaurant, a user can see details about the restaurant's inspection history
A user can comment on a restaurant
Other users can reply to a user's comments.

**Comment by jshawl** [comment]
:+1:  Does the JY mean you're working Jared?

**Comment by jshawl** [comment]
Also please add your user stories to a folder called `planning` in your repo
