### ISSUE TITLE
Project 4 - Pitch

### ISSUE THREAD

**Issue by hellostella** [ga-dc/wdidc5_project4#5]
Everyone loves meeting their favorite athletes, especially kids to get an autograph. For this application, a user will be able to input their favorite team and get location results for where the best location is to obtain autographs or meet the players at that teams stadium and/or city. Users will be allowed to contribute by adding locations, provide stories and ratings of their experiences at each location, and updating any events their team may be holding.

**Comment by jshawl** [comment]
:+1: Awesome idea! Are there any API's available that provide team information? Like team players and their hometowns?
