### ISSUE TITLE
Added ERD

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/wdidc5_project4#55]
https://github.com/lmdragun/escapethecall/blob/master/planning/initial_erd.jpeg

**Comment by jrhorn424** [comment]
This looks like a relatively flat structure. Not sure if that's what you were going for. I'd like to see a traditional relationship diagram when we speak. It doesn't have to be detailed, just give me a general sketch of how your entities relate.

As it stands, this sort of structure lends itself to localstorage and mongo, so if that's the direction you wanted to go, that could work.
