### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by presto2116** [ga-dc/wdidc5_project4#59]
Here is the repo again. ERD is in planning
https://github.com/presto2116/get-out-and-play

and here is the link to the actual ERD 
https://github.com/presto2116/get-out-and-play/blob/master/planning/ERD-First_Draft.JPG
First draft because I believe that I will be changing a few things around but, at least I have a start (sorry the image is sideways, Github doesn't like to show proper rotation)

**Comment by adambray** [comment]
Looks good!

It's unclear in you ERD though, how you're tracking when users have registered for an event. I would consider something like a Registration model that joins users and activities.

-Adam
