### ISSUE TITLE
Project 4 Barley 

### ISSUE THREAD

**Issue by brad-foster** [ga-dc/wdidc5_project4#6]
This is a web application for beer drinkers that introduces the user to a pyramid of beers of increasing complexity and sophistication. It's part education and part motivation to up your beer knowledge while giving context and an interactive visual hierarchy to track and log your progress while trying new beers.

**Comment by RobertAKARobin** [comment]
:+1:

**Comment by RobertAKARobin** [comment]
Just be careful about scoping your project. This sounds very visual, and it's easy for visual projects to become huge and hard to control.
