### ISSUE TITLE
w11d02 and d03 hw

### ISSUE THREAD

**Issue by greenes** [ga-dc/wdidc5_project4#64]
I changed my topic from my original idea: 

https://github.com/greenes/goTogether

**Comment by adambray** [comment]
Hey Sarah,

This looks good too. Do you have a sense of what APIs you're going to use for attractions, accommodations, etc? I feel like that's also some thing you'll want to find / validate early on since your app will depend heavily on it.

-Adam

**Comment by greenes** [comment]
For the accommodations I am thinking of Zilyo,
https://www.mashape.com/zilyo/zilyo, and for the attractions and
restaurants I am thinking Yelp. I think Yelp should work well, but I am not
sure about Zilyo yet since it seems like you can only search location with
longitude and latitude, so I may have to find another one.

**Comment by adambray** [comment]
Hey Sarah,

Let's talk about this in our meeting today. I suspect there are ways to get the appropriate lat / long for the Zilyo API.

-Adam
