### ISSUE TITLE
w11d03

### ISSUE THREAD

**Issue by julia-rose** [ga-dc/wdidc5_project4#66]
I don't know why this image uploaded sideways. It's normal on my computer, I swear. Also, my (super sketchy) wireframe sketches are in there now.

https://github.com/julia-rose/wdi_project4/blob/master/planning/erds.jpg

**Comment by jrhorn424** [comment]
Wireframes look great! I like how each view has a simple interaction component.

Having the rating structure as part of your schema is odd. Can you talk to me about why you wanted to do it that way? I would have guessed that each guest submits a rating and that rating is stored as an integer.

Also, I question the need to store flags and questions in the first place. Do we want a history in the MVP? It's fine to do so, but you're approaching it in a way that makes me nervous: serializing ruby data structures as strings in a column (you might hear that called storing "blobs").
