### ISSUE TITLE
ERD's

### ISSUE THREAD

**Issue by britbrith4** [ga-dc/wdidc5_project4#68]
https://github.com/britbrith4/celebrico

**Comment by britbrith4** [comment]
I am not sure if I submitted everything to the correct place. All of the homework's from this week are in my repo

**Comment by mattscilipoti** [comment]
Thanks for the clarification.  You are quite close.  I was expecting a folder named "planning" that had documents in it (ERD.jpg, UserStories.md, or similar).  This makes it easy for you organize your code in other dirs.

Your stories and ERD reflect your topic well.  Looking at this info, I expect you to nail this.
