### ISSUE TITLE
Project 4 - Lilypad

### ISSUE THREAD

**Issue by greenes** [ga-dc/wdidc5_project4#7]
An application that allows users to enter their address and see a profile of their home's energy usage in an easily digestible format. They will be able to see their energy usage at specific points in time, so they can pinpoint when they are using the most energy. This will help users take control of their energy usage and aim to lower it and save money.

**Comment by adambray** [comment]
Hey Sarah,

I really love the idea for this app. It seems like something you're passionate about, and that could be really interesting and useful (not to mention a perfect demonstration of what we've covered in class).

My biggest concern would be knowing where you're going to get the data from.... do you have an API in mind, or are you planning to fake out the data?

-Adam
