### ISSUE TITLE
Project 4 User Stories - DJ

### ISSUE THREAD

**Issue by dmjurg** [ga-dc/wdidc5_project4#70]
I want to go to a music festival this summer, but I'm overwhelmed by options
I like these three bands, are they playing anywhere together?
What festivals are geographically closest to me?
Who is playing at X festival?
I am attending a festival and I want to connect with others who are going

https://github.com/dmjurg/best_festies

**Comment by mattscilipoti** [comment]
I see you are starting on the planning.  I expect that some drawings of your forms/screens and an ERD would help clarify your project.
