### ISSUE TITLE
Project 4 Wireframes/User Stories and ERDs

### ISSUE THREAD

**Issue by keithknox** [ga-dc/wdidc5_project4#71]
User stories: https://github.com/keithknox/keiths_cookbook/blob/master/planning/user_stories

Wireframes: https://github.com/keithknox/keiths_cookbook/tree/master/planning/wireframes

ERDs: https://github.com/keithknox/keiths_cookbook/tree/master/planning/erds

**Comment by jrhorn424** [comment]
Everything looks excellent and well-scoped. Your wireframes are comprehensive, and I can get an idea of the page flow through your app. The data model is spot-on. :+1: :facepunch:
