### ISSUE TITLE
ERD sketch

### ISSUE THREAD

**Issue by tpeters0** [ga-dc/wdidc5_project4#74]
I'm going to experiment with some things this weekend to get a better idea of things I want to try/ think I'll be able to do aside from the 'wheel' that will involve user input.

The possible erds are on the top and left.  The other diagrams are concept brainstorming.
https://github.com/tpeters0/DomesticViolence/blob/master/planning/possible_erds_and_sketches.jpg

**Comment by jshawl** [comment]
:+1: ERD's look good, though I'm not sure what you mean by virtual tshirt and story building. We can discuss further tomorrow!
