### ISSUE TITLE
Solved!: Sprockets::ArgumentError at / require_tree argument must be a directory

### ISSUE THREAD

**Issue by presto2116** [ga-dc/wdidc5_project4#77]
Trying to set up a rails app with backbone. I have established all my folders and files. In my application.js I have required:

```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require underscore
//= require backbone
//= require handlebars.runtime
//= require_tree ./templates
//= require_tree ./backbone/routers
//= require_tree ./backbone/models
//= require_tree ./backbone/collections
//= require_tree ./backbone/views
//= require backbone_rails_sync
//= require backbone_datalink
//= require backbone/get_out_and_play
//= require_tree .

$(document).ready(loadGetOutAndPlayApp);
        function loadGetOutAndPlayApp(){
            mainCollection = new ActivitiesCollection();
            mainCollectionView = new ActivitiesListView({collection: mainCollection})
            mainCollection.fetch();
        }
```

Still confused by the backbone/get_out_and_play. It was made for me when I set up the backbone gem. I dont see where I am requiring a tree that isn't a directory. Am i missing something?

**Comment by presto2116** [comment]
![screen shot 2015-06-01 at 12 44 24 pm](https://cloud.githubusercontent.com/assets/9746108/7918059/c201b8ce-085c-11e5-98a1-bcef6014e756.png)

**Comment by jrhorn424** [comment]
Make sure all of these directories exist:

```
//= require_tree ./templates
//= require_tree ./backbone/routers
//= require_tree ./backbone/models
//= require_tree ./backbone/collections
//= require_tree ./backbone/views
```

**Comment by jrhorn424** [comment]
What is your directory structure under assets?

**Comment by presto2116** [comment]
├── images
├── javascripts
│   ├── application.js
│   ├── backbone
│   │   ├── collections
│   │   │   └── activitiesCollection.js
│   │   ├── get_out_and_play.js.coffee
│   │   ├── models
│   │   │   └── activityModel.js
│   │   ├── routers
│   │   └── views
│   │       ├── activitiesListView.js
│   │       └── activityView.js
│   └── templates
│       └── activities
│           └── activity.hbs
└── stylesheets
    └── application.css

**Comment by jrhorn424** [comment]
Your templates directory is a child of `backbone` instead of `javascripts`.

Edit: My mistake. Come see me if you're still having this issue.

**Comment by presto2116** [comment]
![screen shot 2015-06-01 at 12 56 47 pm](https://cloud.githubusercontent.com/assets/9746108/7918226/c38a7982-085d-11e5-9ba9-cf3e70464933.png)

**Comment by presto2116** [comment]
![screen shot 2015-06-01 at 12 57 06 pm](https://cloud.githubusercontent.com/assets/9746108/7918229/c8251f38-085d-11e5-95a0-bd17ca1022ca.png)

**Comment by presto2116** [comment]
isn't templates a child of javascripts?

**Comment by jrhorn424** [comment]
Yes, my mistake. Did you check the other directories? Did you restart your server?

**Comment by presto2116** [comment]
what other directories would mess with my application.js?

I tried some trial and error and it seems if i delete both:

//= require backbone/get_out_and_play
//= require_tree .

It works.

**Comment by jrhorn424** [comment]
You shouldn't need to delete `//= require_tree .`.

**Comment by adambray** [comment]
It looks like it's because your `application.js` is nested under templates?

**Comment by adambray** [comment]
At least according to your screenshot.

**Comment by presto2116** [comment]
Solution: since I used backbone-rails gem, it created my file structure in the backbone folder. since I was using a different structure, it kept hitting an error since a tree didn't exist. Deleted getoutandplay.js.coffee and now everything works. thanks for the help @jrhorn424, Also thanks @adambray you also caught the problem
