### ISSUE TITLE
devise routes error 

### ISSUE THREAD

**Issue by uhhlittle** [ga-dc/wdidc5_project4#79]
![screen shot 2015-06-01 at 2 35 30 pm](https://cloud.githubusercontent.com/assets/11261151/7920245/be3637a6-086b-11e5-8fde-ca2df5f68d12.png)

HAiiiiiiiiii, 

I am receiving an error that no route matches GET user/sign_out when i try to sign out

application.html.erb

`<%if current_user %>
          <li><em><%= link_to "Welcome #{current_user.email}", '/profile'%></em></li>
          <li>  <%= link_to 'Signout', destroy_user_session_path, :method => :delete, class: "sign_out" %> </li>
      <% else %>
        <li>  <%= link_to "Sign up", new_user_registration_path, class: "sign_up" %> </li>
        <li>  <%= link_to "Login", new_user_session_path, class: "login" %> </li>
      <% end %>`

tried creating custom route in routes.rb

`devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end`

**Comment by jshawl** [comment]
can you remove `do get '/users/sign_out' => 'devise/sessions#destroy' end`

why create a custom route?

**Comment by jshawl** [comment]
also, it should be a delete request, not get. try clicking the link instead of typing in the url manually

**Comment by andrewsunglaekim** [comment]
got it working, after getting rid of custom route, it was a problem with sprockets and asset pipeline, which i guess messes with the delete route.. somehow?

**Comment by jrhorn424** [comment]
@andrewsunglaekim @uhhlittle I've seen instances where the devise templates do not include the "delete" method option when they're installed into your views folder.
