### ISSUE TITLE
Project 4

### ISSUE THREAD

**Issue by KMG112** [ga-dc/wdidc5_project4#8]
A game where a user drags and drops words to create a new sentence. When the user clicks new game, they are prompted with a list of six words that are capable of beginning a sentence. The user picks a word, and is then given six more random words. this happens for a predetermined number of words, and by the end the user has a new sentence with random meaning.

**Comment by jrhorn424** [comment]
This could be really fun and entertaining. I imagine it being used as a party game!

I'd like to see your user stories and wireframes. Please open a new issue when those are uploaded. Thanks!
