### ISSUE TITLE
username new_session_path not responding 

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5_project4#81]
I can see it in terminal that it responded to the request but I don't see it on the webpage
`Processing by Devise::SessionsController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"bM12ii80W2UPTzopnvbRoSlfg8wRnND3Z1xMBJmgIUXP124K1U/nvz/I66EWOhCjGg2Qd6djiweROh6HLJHWRQ==", "user"=>{"username"=>"thewebdev", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Log in"}
  Rendered users/shared/_links.html.erb (0.2ms)
  Rendered users/sessions/new.html.erb within layouts/application (2.7ms)
Completed 200 OK in 85ms (Views: 23.1ms | ActiveRecord: 0.0ms)`

**Comment by RobertAKARobin** [comment]
Seems to be working for me:

![screen shot 2015-06-01 at 8 00 09 pm](https://cloud.githubusercontent.com/assets/6268177/7925925/e15fa302-0898-11e5-84e4-a9d6a07938ed.png)

**Comment by RobertAKARobin** [comment]
`<%= current_user.username %>` wasn't in the code.
