### ISSUE TITLE
to key error or nil class error

### ISSUE THREAD

**Issue by janicemin** [ga-dc/wdidc5_project4#82]
![screen shot 2015-06-02 at 9 00 48 am](https://cloud.githubusercontent.com/assets/11448897/7936345/37ab1f94-0906-11e5-95ff-ece9f27446d7.png)

i tried switching my code in the new.html.erb file from:

```
<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
```

to

```
<% @user = User.all %>
<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
```

and am getting a to_key error. 

help?

**Comment by janicemin** [comment]
here is my github: https://github.com/janicemin/breakupbud

**Comment by RobertAKARobin** [comment]
It's working fine for me! I made the same switch you did above:

```
<h2> User List <h2>

<div class = "users">
  <% @users = User.all %>
    <% for user in @users %>
      <div class = "user">
        <strong><%= link_to user.username, user_path(user) %></strong>
        <%= link_to "Add Friend", user_friendships_path(:friend_id => user), :method => :post %>
      </div>
    <% end %>
</div>
```

**Comment by RobertAKARobin** [comment]
![screen shot 2015-06-02 at 9 18 15 am](https://cloud.githubusercontent.com/assets/6268177/7936598/56f281e2-0908-11e5-9c68-e8ed1d8208c6.png)

**Comment by janicemin** [comment]
oh, i'm on add a new friend...that's another error i was going to ask about. not sure why my add friend link isn't showing?

**Comment by RobertAKARobin** [comment]
You have it inside `<% for user in @users %>`. If you don't have any users, then it won't show.

**Comment by RobertAKARobin** [comment]
Oh, I'm sorry, I was in the wrong file — `users/`. I didn't see this was in `users/new`. One sec.

**Comment by janicemin** [comment]
duh. okay...but i'm still not sure why the new friend form on new.html.erb  keeps getting the error of nil or to_key ?

**Comment by RobertAKARobin** [comment]
Try deleting `<% @user = User.all %>` on line 10. You already defined `@user` in your controller.

**Comment by RobertAKARobin** [comment]
When I delete that, it starts working fine

**Comment by RobertAKARobin** [comment]
![screen shot 2015-06-02 at 9 24 55 am](https://cloud.githubusercontent.com/assets/6268177/7936719/40048498-0909-11e5-992e-2844c3f56916.png)

**Comment by janicemin** [comment]
not sure why mine's not working...that's how i originally had it set up. then changed it because i got this error: undefined method `username' for #<User id: nil> which i'm still getting after i delete that line...

**Comment by RobertAKARobin** [comment]
Can you copy and paste the error?

**Comment by janicemin** [comment]
![screen shot 2015-06-02 at 9 29 17 am](https://cloud.githubusercontent.com/assets/11448897/7936818/ef94218e-0909-11e5-9d36-b192c24d5eb4.png)

**Comment by RobertAKARobin** [comment]
Can you show me what the `new` method in your Users controller looks like? Mine is:

```
    def new
        @user = User.new
    end
```

**Comment by janicemin** [comment]
yup, that's what's on mine.

**Comment by RobertAKARobin** [comment]
It sounds like your `User` table doesn't have a `username` column. Have you run `rake db:migrate` recently?

**Comment by janicemin** [comment]
yeap. and i just did another one...

**Comment by janicemin** [comment]
and yeah, now that i'm looking at the table, it doesn't have that column...but i included it in my migration files?

**Comment by RobertAKARobin** [comment]
Migration files are only run once. That's why each one has a date at the beginning of its file name. It made the `username` column for me because this was my first time running any of the migration files.

**Comment by RobertAKARobin** [comment]
You'll need to either drop your whole app and rebuild everything — OR, much better solution, create a new migration file. Check this out: http://edgeguides.rubyonrails.org/active_record_migrations.html#creating-a-migration

**Comment by janicemin** [comment]
yeah, i did drop and migrated again, but the table is still messed up. i'll try and figure out the solution you posted via the link

**Comment by RobertAKARobin** [comment]
You'll need to do `rails g migration AddUsernameToUsers username:string`

**Comment by RobertAKARobin** [comment]
And then `rake db:migrate`

**Comment by jrhorn424** [comment]
Another opinion here: there's nothing wrong with destroying a local database, especially when figuring out new migrations. You just can't do this on a production server.

Can you point us to the migration where you already added `username` to the appropriate table?

Let us know what progress you make.
