### ISSUE TITLE
submitting a form but not saving to database

### ISSUE THREAD

**Issue by janicemin** [ga-dc/wdidc5_project4#86]

**Comment by janicemin** [comment]
in my new.html.erb

```<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

  <p>
    <%= f.label :password, '8+ characters' %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit %></p>
<% end %>```

and in my controller
```class UsersController < ApplicationController

```
def index
    @users = User.all
end

def show
    @user = User.find(params[:id])
end

def new
    @user = User.new
end

def create
    @user = User.new(params[:username], params[:password])
    if @user.save
        redirect_to @user
    else
        render :new
    end
end

def edit
end

def update
end

def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
end
```

end```

**Comment by jshawl** [comment]
i would try adding `binding.pry` in your create method. maybe the validation is failing?

**Comment by andrewsunglaekim** [comment]
the code looks accurate, the only thing that i can see potentially is password field might be messing it up? Can you try changing that to text field and see if that works? Additionally, you may want to use strong params.

**Comment by janicemin** [comment]
yeah, i put in the strong params as per jeff's advice and it works now :)

**Comment by andrewsunglaekim** [comment]
cool, im gonna close this issue, open a new one if something goes wrong!
