### ISSUE TITLE
Underscore not loading

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5_project4#87]
I am getting this error: 
![image](https://cloud.githubusercontent.com/assets/11448967/7942074/b43873cc-0929-11e5-9bb0-e6fbc869d56c.png)
Even though I have included the gem in my Gemfile:
![image](https://cloud.githubusercontent.com/assets/11448967/7942090/ca0daa6e-0929-11e5-811d-0da926274ecf.png)
And I've required it in my application.js:
![image](https://cloud.githubusercontent.com/assets/11448967/7942122/fc55ac56-0929-11e5-8084-d0374d2aaec6.png)

**Comment by jshawl** [comment]
Did you try restarting the server after a `bundle install`?

**Comment by Tuzibun** [comment]
Yep, just did that and it's all working now.  Duh.  Thanks!
