### ISSUE TITLE
undefined method that I don't understand why

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5_project4#88]
![screen shot 2015-06-02 at 3 05 27 pm](https://cloud.githubusercontent.com/assets/9599485/7944498/f7acf2fe-0938-11e5-9737-9677c3bd5051.png)

**Comment by RobertAKARobin** [comment]
It's saying the User model doesn't have a column called `mailboxer_email`

**Comment by AliTopal89** [comment]
oh silly me got it 

solved: 
-user.rb-
def mailboxer_email(object)
    email
  end
