### ISSUE TITLE
undefined local variable, but it is defined

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5_project4#89]
![image](https://cloud.githubusercontent.com/assets/11448967/7944554/5d0bceae-0939-11e5-8fcf-e210eddca468.png)

from here:
![image](https://cloud.githubusercontent.com/assets/11448967/7944570/796b1bfe-0939-11e5-977d-d40c7b99da7b.png)

but, 
![image](https://cloud.githubusercontent.com/assets/11448967/7944561/6a8a64b4-0939-11e5-9b8f-4c3907a6a9ad.png)

**Comment by jshawl** [comment]
Your erb is complaining about the undefined variable. Are you using handlebars with Backbone?

i.e. ruby doesn't know about that variable.

**Comment by Tuzibun** [comment]
i haven't done anything with handlebars yet, but i've included the gem

**Comment by RobertAKARobin** [comment]
`first_name` is a Javascript variable, and you're calling `<%= first_name %>`, which is a Ruby variable. You can't just toss variables around between JS and Ruby that way.

**Comment by Tuzibun** [comment]
ah ok.  I used handlebars instead.
