### ISSUE TITLE
login is not working again

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5_project4#90]
![screen shot 2015-06-02 at 3 19 18 pm](https://cloud.githubusercontent.com/assets/9599485/7944766/be82d32a-093a-11e5-970d-8aeca852925d.png)

**Comment by jshawl** [comment]
can you create an account?

**Comment by RobertAKARobin** [comment]
@jshawl Looking at it now, but not sure what the problem is. You can sign up, and then use your account no problem. The problem is just when you log back in again.
