### ISSUE TITLE
Event listener isn't listening

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5_project4#92]
I have this code:
![image](https://cloud.githubusercontent.com/assets/11448967/7948602/5e4eda12-0953-11e5-8ead-eb9005ab3ffb.png)

But when I click the add button, nothing happens (nothing in the console, nothing on the screen)...
![image](https://cloud.githubusercontent.com/assets/11448967/7948620/85d11082-0953-11e5-9fbb-c1502bd42352.png)

whyyyyyy

**Comment by RobertAKARobin** [comment]
Where is that `replace` property it's talking about?

**Comment by Tuzibun** [comment]
no idea... somewhere in one of the files that was magically created

**Comment by RobertAKARobin** [comment]
Try commenting out `classroom1.add()`, and see if that keeps the error from showing. Then comment it back in, and try the `student.toJSON()` bit. That way you can triangulate the problematic bit.

Also, looking at the code you included, I don't see where the variable `classroom1` comes from...?

**Comment by Tuzibun** [comment]
no luck.  I tried putting an alert right after the document ready line and that doesn't even show up...

**Comment by RobertAKARobin** [comment]
Wat. Try commenting out the whole `document.ready` block.

**Comment by Tuzibun** [comment]
still getting this: 
![image](https://cloud.githubusercontent.com/assets/11448967/7948976/1ac50272-0957-11e5-8360-63ebaa971e4a.png)

I think it's coming from my use of _.each here: 
![image](https://cloud.githubusercontent.com/assets/11448967/7948982/3387db22-0957-11e5-86c3-b7d9735ed9ae.png)

**Comment by RobertAKARobin** [comment]
Oh. Any chance you could push all this to Github?

**Comment by Tuzibun** [comment]
pushed to: https://github.com/Tuzibun/playdate

**Comment by RobertAKARobin** [comment]
Do the same thing, except without uncommenting: starting from the bottom, comment crap out until the problem stops happening. Then let us know where the problem was.

**Comment by Tuzibun** [comment]
AHA!  The problem was this line:
![image](https://cloud.githubusercontent.com/assets/11448967/7949147/36e19752-0959-11e5-88bf-d43b3e17ceb9.png)
So basically, I can't instantiate a new view of all the students...

**Comment by RobertAKARobin** [comment]
Woo! Interesting. Uh, does that mean you can fix the problem, or are you still stuck?

**Comment by Tuzibun** [comment]
still stuck because I can't get the newly added student to show up

**Comment by Tuzibun** [comment]
I think the problem is either with jQuery not being able to find what I want (the StudentListView) or with underscore not knowing what to do with the _.each function...

**Comment by RobertAKARobin** [comment]
If the problem occurs when I call `new StudentView()` then my next step would be to do the progressive commenting-out thing inside StudentView and narrow it down further. Otherwise we're just staring at a wall of code trying to find a needle in a haystack.

**Comment by jrhorn424** [comment]
Since this code is in a document ready, I wonder if it works when you refresh the page?

I highly suspect this is a turbolinks issue. When you add things to dinner ready, you also have to add them to the page load event.

Search the project 3 repo issues for "turbolinks" for more info.

**Comment by RobertAKARobin** [comment]
"Dinner ready"

**Comment by Tuzibun** [comment]
I'm getting a new error... progress?
![image](https://cloud.githubusercontent.com/assets/11448967/7950222/95994c16-0965-11e5-9bda-118b406f653b.png)

The page loads, but when I click the Add button, the new student doesn't appear on the page and i get the error above.

**Comment by Tuzibun** [comment]
I've changed the document ready stuff (according to this: http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links, but I'm STILL getting this error:
![image](https://cloud.githubusercontent.com/assets/11448967/7950656/dd3a4cf4-096b-11e5-96c2-15ece091a09b.png)

**Comment by Tuzibun** [comment]
Problem solved.  I was passing the constructor function instead of the new student model.

**Comment by jrhorn424** [comment]
> "Dinner ready"

I lol'd.
