### ISSUE TITLE
route confusion

### ISSUE THREAD

**Issue by janicemin** [ga-dc/wdidc5_project4#93]
![screen shot 2015-06-02 at 6 30 57 pm](https://cloud.githubusercontent.com/assets/11448897/7948869/2ecc245e-0956-11e5-8db1-1922f9ec78fb.png)

```
<h2>Create Your Profile<h2>
    <%= form_for new_profile_path(@profile) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %><br>
```

**Comment by RobertAKARobin** [comment]
You don't seem to have a `profiles/show` route. Does that show up in `rake routes`? Is it defined in your `profiles` controller?
