### ISSUE TITLE
Setting up the marker for the MapBox API

### ISSUE THREAD

**Issue by JYamauchi** [ga-dc/wdidc5_project4#95]
I created the javascript to create a map element with the search method. How do I create a marker in the MapBox API? 

I am trying to figure out how to create a coordinate for the marker but I am not sure where to start. Should I create a DB migration file that contains longitude and latitude?  

Here is the code I put on the application.html. 

`````` <script>
        L.mapbox.accessToken = 'pk.eyJ1IjoiaGF3YWlpemVybyIsImEiOiJlMmRlM2YwM2VlZWExODE0MGJhNzY2OGZlYzNlMDY2NiJ9.bb6hiEKb0vpXFkNRB4y78w';
        var map = L.mapbox.map('map', 'hawaiizero.75dae6ca')
            .setView([37, -77], 5)
            .addControl(L.mapbox.geocoderControl('mapbox.places'));
        var marker = L.marker([37, -77], 5).addTo(map);
        var markerHtml = 'This place is weird';
        marker.bindPopup(markerHtml);
        var features = [];

    </script>``` 
``````

**Comment by RobertAKARobin** [comment]
Can you tell me what you mean by "create a coordinate"? Aren't the coordinates for the above code `37, -77`?

**Comment by JYamauchi** [comment]
I think I want to create a Jquery code to update the coordinates like this: 
var marker = L.marker([{longitude}, {latitude}], {zoom}).addTo(map); 

How do I create the search input box so that the input will "call" {longitude} or {latitude}?

**Comment by RobertAKARobin** [comment]
If you want to get the latitude and longitude from the user, you could do something like this (if you're using jQuery):
HTML:

```
<input type="text" id="latitude" />
<input type="text" id="longitude" />
<input type="text" id="zoom" />
<button type="button" id="search">Click me!</button>
```

jQuery:

```
$("#search").click(function(){
  var latitude = $("#latitude").val();
  var longitude = $("#longitude").val();
  var zoom = $("#zoom").val();
  var marker = L.marker([latitude, longitude], zoom).addTo(map);
});
```

Not jQuery:

```
document.getElementById("search").addEventListener("click", function(){
  var latitude = document.getElementById("latitude").value;
  var longitude = document.getElementById("longitude").value;
  var zoom = document.getElementById("zoom").value;
  var marker = L.marker([latitude, longitude], zoom).addTo(map);
});
```
