### ISSUE TITLE
All the problems, everywhere

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5_project4#96]
Ok, the first problem is probably a quick fix:
I created a logo (playdate.tif) and I've placed it in the app/assets/images directory, but the html.erb page can't find it:
![image](https://cloud.githubusercontent.com/assets/11448967/7965991/16397524-09ef-11e5-9700-9b5639a9158a.png)

Problem 2:
I can enter information into the form, and when I click the add button, the console shows me that my new student has been created (the attribute information has been filled in), but it will not create a new tr under the form row.

I have this code to tell it how to make the new tr:
![image](https://cloud.githubusercontent.com/assets/11448967/7966035/61808b4e-09ef-11e5-8f78-ab95a3ca63b7.png)

And I want it to take the information from the form:
![image](https://cloud.githubusercontent.com/assets/11448967/7966062/8c1de216-09ef-11e5-96e0-f28df988470c.png)

And add it to the table:
![image](https://cloud.githubusercontent.com/assets/11448967/7966076/9ee7fcc4-09ef-11e5-84ba-a08b3cfa0433.png)

**Comment by jshawl** [comment]
for the html.erb page, how are you linking to the image?

**Comment by Tuzibun** [comment]
![image](https://cloud.githubusercontent.com/assets/11448967/7966209/7dd26b90-09f0-11e5-8668-1cffd58319c4.png)

**Comment by Tuzibun** [comment]
I've changed the template to use clown hats instead...
![image](https://cloud.githubusercontent.com/assets/11448967/7966569/e65834cc-09f2-11e5-915e-8a9f6eafdb5d.png)

but now I get this:
![image](https://cloud.githubusercontent.com/assets/11448967/7966571/f06e0e82-09f2-11e5-89b4-9ebbb99f5e15.png)

I thought maybe I could use ruby because this is all in the application.html.erb file?

**Comment by jrhorn424** [comment]
Are you using handlebars? If so, you need to include two `%` otherwise rails thinks it's ERB. Instead of `<%= first_name %>` it should be `<%%= first_name %>`.

**Comment by jrhorn424** [comment]
For the image issue, I believe you need `<%= image_tag(asset_path('playdate.tif')) %>` or something similar.

**Comment by Tuzibun** [comment]
I gave up on handlebars, because it wasn't working.  Now I'm just trying to do anything to get it to know what those variables are.  Right now I'm just going back to the very beginning and rebuilding everything in rails, without any backbone.

**Comment by Tuzibun** [comment]
Also, the <%= image_tag(asset_path('playdate.tif')) %> didn't work.

**Comment by jrhorn424** [comment]
For your image issue: http://stackoverflow.com/a/19232244/402618

**Comment by jrhorn424** [comment]
If you aren't using Handlebars or Backbone, rails needs to know where to find `first_name`. Is it attached to the user object? profile? Come find me if you want to walk through it. At the work tables.

**Comment by jrhorn424** [comment]
Also, if you aren't using handlebars or backbone, I'm not sure you still need a template in your view.

**Comment by Tuzibun** [comment]
fixed the image issue by hosting it on flickr and just using an img src tag.

giving up on backbone and starting over in rails
