### ISSUE TITLE
posting to mongo db with ajax

### ISSUE THREAD

**Issue by DamonMd** [ga-dc/wdidc5_project4#97]
Can I post directly to my db/collection in the ajax call? and if so, how

**Comment by RobertAKARobin** [comment]
Nope. That's because it would be REALLY insecure. Anyone could just modify your Javascript and do whatever they want with your DB, unless you had some goofy complicated security thing built in.

**Comment by jrhorn424** [comment]
Yep, you have to go through your web server. If this answers your question, would you mind closing the issue?
