### ISSUE TITLE
Unable to append data to table - ArgumentError: invalid byte sequence in UTF-8?

### ISSUE THREAD

**Issue by mugshepherd** [ga-dc/wdidc5_project4#98]
I have two tables that have a one to one relationship between them.  
I'm trying to append a field of data from one file to the other (main) file
I keep getting the above error when trying to merge them.  on using code to address the problem, none of the values are appended to the other table.  
I can't tell if the error has to do with the UTF-8 error (and code used to address it), or if I am doing something wrong.  

seed data file

```
    line_num = 0
    text=File.open('db/yelp_crosswalk.csv').read
    text.each_line do |line|
        if ! line.valid_encoding?
        line = line.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('UTF-8')
        end
        print "#{line_num += 1} #{line}"
        data = line.split(",")
        yelpid = data[1]
        permitid = data[0]
        r = Restaurant.find_by(permit_id: permitid)
        if r
            r.yelp_id = yelpid
            r.save
        end
    end
```

"yelp_crosswalk.csv"

```
permit_id,yelp_id
1434,
```

restaurants.csv

```
permit_id,name,address,latitude,longitude
1434,STAND N SNACK,"1133 15TH ST NW Washington, DC 20005",38.90440268,-77.03446626
```

**Comment by jrhorn424** [comment]
It isn't clear what your issue is. Are you merging two files? Are you trying to seed from CSV? Would you mind fencing off your code blocks using triple-backticks, and proper spacing?

``````
```
# code goes here
```
``````

**Comment by mugshepherd** [comment]
Sorry - first time posting code to an issue here. 

I am trying to merge two files as we discussed yesterday.  The merge is rejected due to the UTF-8 issue noted above when I run the merge as i normally would, and when I try to take the UTF-8 issue into account, the data I am trying to append does not get added.  I'm not sure what I'm doing wrong.  

Would love to discuss this in person.  

Thanks - Toby

Seeds.db

```
require 'csv'
    puts "importing restaurants"
    csv_text = File.read('db/restaurants.csv')
    csv = CSV.parse(csv_text, :headers => true, converters: :numeric)
    csv.each do |row|
      Restaurant.create!(row.to_hash)
    end

    text=File.open('db/yelp_crosswalk.csv').read
    text.each_line do |line|
        if ! line.valid_encoding?
        line = line.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('UTF-8')
        end
        data = line.split(",")
        yelpid = data[1]
        permitid = data[0]
        r = Restaurant.find_by(permit_id: permitid)
        if r
            r.yelp_id = yelpid
            r.save
        end
    end
```

Restaurant migration

```
class CreateRestaurants < ActiveRecord::Migration
  def change
    create_table :restaurants do |t|
        t.text :name
        t.integer :permit_id
        t.text :address
        t.decimal :latitude
        t.decimal :longitude
        t.text :yelp_id

        t.timestamps null: false
    end
  end
end
```

Restaurant model:

```
class Restaurant < ActiveRecord::Base
    has_many :inspections
end
```

restaurants.csv

```
permit_id,name,address,latitude,longitude
1434,STAND N SNACK,"1133 15TH ST NW Washington, DC 20005",38.90440268,-77.03446626
etc.
```

yahoo_crosswalk.csv

```
permit_id,yelp_id
1434,
```

**Comment by RobertAKARobin** [comment]
I'm confused as to why you have to encode this stuff in the first place... Generally everything is UTF8-compatible by default. Does this not work if you get rid of all the encoding?

**Comment by mugshepherd** [comment]
it keeps interrupting my import.  can I pop over and chat?  

![screen shot 2015-06-03 at 4 39 59 pm](https://cloud.githubusercontent.com/assets/7784700/7970920/39732858-0a0f-11e5-9151-f0e5d32ae1dd.png)

**Comment by RobertAKARobin** [comment]
My understanding is Jesse asked you to manually input this since creating the input dynamically this way isn't essential to your MVP. I'd rather you defer to his judgment.

**Comment by jrhorn424** [comment]
Resolution notes:
- When parsing CSV, use the `CSV.foreach` method to minimize issues using `File.open` and `File.read`.
- Sometimes, you have to specify encoding as an option to the `CSV.foreach` method, especially when the CSV file might have come from Excel.
