### ISSUE TITLE
Deploying a node/mongo/backbone app to heroku 

### ISSUE THREAD

**Issue by brad-foster** [ga-dc/wdidc5_project4#99]
So the app runs fine locally, but won't display on heroku. It's giving a 503 error saying the server isn't responding.

The main heroku logs error I'm seeing:
- Error: connect ECONNREFUSED 
- npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"

After googling the errors and looking into the issue in general I'm pretty sure the solution lies in my server.js or package.json file. I've tried a handful of different things with the port and root routes, but I'm pretty stuck at this point. Thanks in advance for any help I really appreciate it!

I'll include the code from those two files below and here's the link to my github repo:
https://github.com/btf5048/Project4

My current server.js file:

```
var express = require('express');
var bodyParser = require('body-parser');
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/barley');

var Schema = mongoose.Schema;

var BeerSchema = new Schema({
  name: String,
  style: String,
  image: String
});

mongoose.model('Beer', BeerSchema);

var Beer = mongoose.model('Beer');

var app = express();

app.use(express.static(__dirname + '/public'));
app.use(bodyParser.json());

app.all('/*', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type");
  res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE");
  next();
});

app.get('/', function(req, res){
  res.sendfile('/public/index.html');
});

app.get('/api/beers', function(req, res){
  Beer.find(function(err, docs){
    docs.forEach(function(item){
      console.log('Received a GET request for _id: ' + item._id);
    });
    res.send(docs);
  });
});

app.post('/api/beers', function(req, res){
  console.log('Received a POST request');
  for (var key in req.body) {
    console.log(key + ': ' + req.body[key]);
  }
  var beer = new Beer(req.body);
  beer.save(function(err, doc){
    res.send(doc);
  });
});

app.delete('/api/beers/:id', function(req, res){
  console.log('Received a DELETE request for _id: ' + req.params.id);
  Beer.remove({_id: req.params.id}, function(err){
    res.send({_id: req.params.id});
  });
});

app.put('/api/beers/:id', function(req, res){
  console.log('Received an UPDATE request for _id: ' + req.params.id);
  Beer.update({_id: req.params.id}, req.body, function(err){
    res.send({_id: req.params.id});
  });
});

var port = process.env.PORT || 3000;

app.listen(port);
console.log('server on ' + port);
```

My current package.json file:

```
{
  "name": "application",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.12.4",
    "express": "^4.12.4",
    "mongoose": "^4.0.4"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/btf5048/Project4"
  }

}
```

**Comment by jshawl** [comment]
What about this SO answer? http://stackoverflow.com/questions/19668218/websocket-not-working-with-socket-io-in-heroku

**Comment by jshawl** [comment]
Also check out https://devcenter.heroku.com/articles/node-websockets

**Comment by jshawl** [comment]
Also you hard coded the port here which might be An issue https://github.com/btf5048/Project4/blob/master/application/public/js/Collections/BeersCollection.js

**Comment by mattscilipoti** [comment]
I think the mongo connection is suspect: `mongoose.connect('mongodb://localhost/barley');
`  What mongo db are you using on heroku?
Here is a "working" example for MongoHQ & heroku: https://github.com/mongolab/hello-mongoose/blob/master/app.js.
